name: Sample Workflow Run

on:
  push:
    branches:
      - main  # Runs the workflow when code is pushed to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  example-job:
    runs-on: ubuntu-latest

    env:
      GLOBAL_MESSAGE: "This is a global message"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print environment variables
        run: |
          echo "Global message: $GLOBAL_MESSAGE"
          echo "GitHub repository: $GITHUB_REPOSITORY"
          echo "GitHub workflow name: $GITHUB_WORKFLOW"
          echo "Current branch: $GITHUB_REF_NAME"

      - name: Use step-level environment variable
        env:
          STEP_VAR: "Step-level variable"
        run: echo "Step message: $STEP_VAR"

      - name: Access a GitHub secret (masked)
        run: echo "Using a secret"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Run a simple script
        run: |
          echo "Running a sample script..."
          echo "Today's date is $(date)"
          echo "This workflow run ID is $GITHUB_RUN_ID"

      - name: Conditional step
        if: github.event_name == 'push'
        run: echo "This step runs only on push events"
